[package]
name = "gameobject"
version = "0.1.0"
edition = "2021"

[lib]
name = "gameobject"
crate-type = ["staticlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "0.2.2"